# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
      
      - name: Get build tag
        id: build_tag
        run: |
          echo "build_tag=$BUILD_DATE" >> $GITHUB_OUTPUT
        env:
          BUILD_DATE: ${{ steps.date.outputs.date }}
  
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
    outputs:
      build_tag: ${{ steps.build_tag.outputs.build_tag }}
          
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    needs: [build]
    secrets:
      DEMO_HOST: ${{ secrets.RESOURCE_GROUP }}
      envPAT: ${{ secrets.envPAT }}
    concurrency: release
    with:
      environment: DEV
      config-path: ${{needs.build.outputs.build_tag}}
      
  deploy-test:
    uses: ./.github/workflows/deploy.yml
    needs: [build, deploy-dev]
    secrets:
      DEMO_HOST: ${{ secrets.RESOURCE_GROUP }}
      envPAT: ${{ secrets.envPAT }}
    concurrency: release
    with:
      environment: TEST
      config-path: ${{needs.build.outputs.build_tag}}
  
