# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: Get build tag
        run: |
          echo "build_tag=$BUILD_DATE-$BUILD_ATTEMPT" >> $GITHUB_ENV
        env:
          BUILD_DATE: ${{ steps.date.outputs.date }}
          BUILD_ATTEMPT: ${{ env.GITHUB_RUN_ATTEMPT }}
  
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    needs: [build]
    secrets: inherit
    concurrency: release
    with: 
      config-path: .github/labeler.yml
      
  deploy-acpt:
    uses: ./.github/workflows/deploy.yml
    needs: [deploy-dev]
    secrets: inherit
    concurrency: release
    with: 
      config-path: .github/labeler.yml
  
