# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on: 
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  create-release:
    uses: ./.github/workflows/_create-release.yml
    with:
      pre_release: false

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [create-release]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Create Release
        run: |
          echo "new tag is: ${{ needs.create-release.outputs.build_tag }}"
          
 
