# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on: 
  push:
    branches: ["main"]
   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
      
      - name: Get build tag
        id: build_tag
        run: |
          echo "build_tag=$BUILD_DATE" >> $GITHUB_OUTPUT
        env:
          BUILD_DATE: ${{ steps.date.outputs.date }}
  
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ vars.NAME }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v.1.0.0
          release_name: Release v.1.0.0
          body: |
            Changes in this Release
            - First Change
            - Second Change
          prerelease: false
      
          
    outputs:
      build_tag: ${{ steps.build_tag.outputs.build_tag }}
          
#  deploy-dev:
#    uses: ./.github/workflows/deploy.yml
#    needs: [build]
#    secrets:
#      DEMO_HOST: ${{ secrets.DEMO_HOST }}
#      envPAT: ${{ secrets.envPAT }}
#    concurrency: release
#    with:
#      environment: dev
#      config-path: ${{needs.build.outputs.build_tag}}
      
#  deploy-test:
#    uses: ./.github/workflows/deploy.yml
#    needs: [build, deploy-dev]
#    secrets:
#      DEMO_HOST: ${{ secrets.DEMO_HOST }}
#      envPAT: ${{ secrets.envPAT }}
#    concurrency: release
#    with:
#      environment: test
#      config-path: ${{needs.build.outputs.build_tag}}
  
