# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: true
        description: Environment to deploy to
        type: string
        default: 'dev'
    secrets:
      envPAT:
        required: true
      DEMO_HOST:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: ${{ inputs.environment }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line with DEMO_HOST
        run: echo ${{secrets.DEMO_HOST }} | sed 's/./& /g'
        
      # Runs a single command using the runners shell
      - name: Run a one-line with envPAT
        run: echo ${{secrets.envPAT }} | sed 's/./& /g'      

      # Runs a set of commands using the runners shell
      - name: Run a one-line with config-path
        run: |
          echo Add other actions with config-path,
          echo ${{ inputs.config-path }}
