name: deploy

on:
  push:
    tags:
      - "*.*.*"
      
jobs:
  # This workflow contains a single job called  "build"
  create-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Taking Tag number
        id: releaseVersion
        run: |
          GIT_TAG=${{github.ref_name}}
          echo "Tag number: $GIT_TAG"   
